package com.example.hectorvera.ezinfo.POJO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RELATION".
 */
public class Relation {

    private Long ParentId;
    private Long ContentId;
    private Long Rank;

    public Relation() {
    }

    public Relation(Long ParentId, Long ContentId, Long Rank) {
        this.ParentId = ParentId;
        this.ContentId = ContentId;
        this.Rank = Rank;
    }

    public Long getParentId() {
        return ParentId;
    }

    public void setParentId(Long ParentId) {
        this.ParentId = ParentId;
    }

    public Long getContentId() {
        return ContentId;
    }

    public void setContentId(Long ContentId) {
        this.ContentId = ContentId;
    }

    public Long getRank() {
        return Rank;
    }

    public void setRank(Long Rank) {
        this.Rank = Rank;
    }

}
